- name: Ensuring nftables pkgs are installed
  yum:
    name:
      - nftables
      - firewalld

- name: Ensuring firewalld is stopped 
  service: 
    name: firewalld 
    state: stopped 
    enabled: no

- name: Ensuring folders exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/sysconfig/nftables.d

- name: Dropping templated nftables rules
  template:
    src: "nftables/{{ item }}"
    dest: "/etc/sysconfig/nftables.d/{{ item }}"
    mode: 0644
  with_items:
    - 01-input-0_head
    - 01-input-z_foot
    - 98-forward-0_head
    - 98-forward-z_foot

- name: Configuring incoming sshd allowed IP
  template:
    src: nftables/01-input-service-default-sshd.policy.j2
    dest: /etc/sysconfig/nftables.d/01-input-allowed-sshd.policy
    mode: 0644

- name: Implementing local ipv4 firewall rule[s], if any
  template: 
    src: nftables/01-input-localrules-policy.j2 
    dest: /etc/sysconfig/nftables.d/01-input-localrules-policy
    mode: 0644
  when: iptables_local_input_rules is defined

- name: Implementing ipv4 blocking/deny rules, if defined
  template:                                                                                                        
    src: nftables/01-input-blocked-denylist.policy.j2
    dest: /etc/sysconfig/nftables.d/01-input-blocked-denylist.policy
    mode: 0644
  when: iptables_block_rules is defined

- name: Clearing ipv4 blocking/deny rules, if undefined
  file:                                                                                                        
    path: /etc/sysconfig/nftables.d/01-input-blocked-denylist.policy
    state: absent
  when: iptables_block_rules is not defined

- name: Implementing ipv6 blocking/deny rules, if defined
  template:                                                                                                        
    src: nftables/01-input-blocked_v6-denylist.policy.j2
    dest: /etc/sysconfig/nftables.d/01-input-blocked_v6-denylist.policy
    mode: 0644
  when: ip6tables_block_rules is defined

- name: Clearing ipv6 blocking/deny rules, if undefined
  file:                                                                                                        
    path: /etc/sysconfig/nftables.d/01-input-blocked_v6-denylist.policy
    state: absent
  when: ip6tables_block_rules is not defined

- name: Configuring external sets/lists to block 
  template:
    src: nftables/01-input-dropped-extlists
    dest: /etc/sysconfig/nftables.d/01-input-dropped-extlists
    mode: 0644


# Whole block to include if host is router/gw (iptables_gw boolean)
- block:
    - name: Enabling ipv4 routing
      sysctl: 
        name: net.ipv4.ip_forward 
        value: 1 
        state: present 
        reload: yes
    - name: Adding forward/NAT rule if needed
      template: 
        src: "nftables/{{ item }}" 
        dest: "/etc/sysconfig/nftables.d/{{ item }}"
        mode: 0644
      with_items:
        - 05-nat-10-postrouting
        - 05-nat-12-prerouting
        - 98-forward-11-allow 
  when: iptables_gw


- name: Building nftables config file
  assemble:
    src: /etc/sysconfig/nftables.d/
    dest: /etc/sysconfig/nftables.conf
  notify: restart_nftables
  register: nftables_config

- name: Reloading nftables rules if changed now
  service: 
    name: nftables 
    state: restarted
  when: nftables_config is changed

- name: Enabling the nftables service
  service: 
    name: "{{ item }}" 
    state: started 
    enabled: yes
  with_items:
    - nftables

- name: Creating config files for external lists to download/insert
  template:
    src: nftables/nftables-lists.cfg.j2
    dest: /etc/nftables-lists.cfg
    mode: 0644  
  notify: nft_lists_refresh

- name: Dropping wrapper to download/refresh lists
  template:
    src: nftables/nft-lists-refresh
    dest: /usr/libexec/centos/nft-list-refresh
    mode: '0755'

- name: Refreshing nft set lists
  cron:
    name: nft setlists refresh
    job: /usr/libexec/centos/nft-list-refresh
    hour: "*/2"
    minute: "35"
    state: present
